apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-s0l0
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-diwf-tenant/rhtap-demo-app/hacbs-test-project-s0l0@sha256:9de46ada346b8af7b351c8716d970c507c618ab808b4beafe08ae09f34248e0a
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
