apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-s0l0
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-s0l0
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-s0l0
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-s0l0
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-s0l0
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-diwf-tenant/rhtap-demo-app/hacbs-test-project-s0l0@sha256:9de46ada346b8af7b351c8716d970c507c618ab808b4beafe08ae09f34248e0a
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
